USE oneTeam;
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 52, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 349, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 72, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 325, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 641, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 431, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 589, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 633, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 329, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, -22, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 29, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 620, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 30, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 407, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, -13, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 634, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 667, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 382, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 495, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 26, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 465, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 652, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 357, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 443, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 441, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 366, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 436, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 432, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 417, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 407, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 381, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 409, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 368, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 383, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 579, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 312, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 368, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 387, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 631, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 660, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 662, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 348, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 363, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 680, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 373, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 113, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, -8, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 329, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 323, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 457, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 41, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 315, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 326, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 475, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 422, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 596, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 623, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 76, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 405, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 514, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 633, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 403, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 372, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 356, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 707, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 494, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 343, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 566, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 713, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 451, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 435, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 316, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 628, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 678, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 571, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 415, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 383, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 674, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 428, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 401, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 358, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 792, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 398, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 646, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 438, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 625, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 296, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 92, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 418, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 56, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 552, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 708, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 411, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 361, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 144, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 668, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 604, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 420, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 304, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 444, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 2115, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 2291, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 1234, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 2245, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 209, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 1346, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 152, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 1796, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 26, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 2006, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 1640, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 1069, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 247, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 2039, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 239, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 49, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 948, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 2186, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 984, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 2067, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 1272, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 39, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 1947, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 1541, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 2069, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 1572, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 1335, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 99, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 1251, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 1074, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 1462, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 1495, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 936, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 125, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 1933, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 2186, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 1614, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 321, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 194, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 997, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 1162, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 1983, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 1486, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 2120, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 2059, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 662, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 799, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 1534, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 1015, "Hello so confused!", false, null, 1);
INSERT INTO timeStamps(videoId, userId, timeStamp, comment, addressedByTeacher, commentType, video)
    VALUES("ZK3O402wf1c", 4, 193, "Hello so confused!", false, null, 1);